### ISSUE TITLE
not getting the binary to run from downloaded zip

### ISSUE THREAD

**Issue by wolftune** [porridge/bambam#112]
downloaded bambam-master.zip

```
$ ./bambam.desktop 
kf.service.services: KApplicationTrader: mimeType "x-scheme-handler/file" not found
```

and then the .desktop file opens in my text editor

I'm using KDE Neon

**Comment by porridge** [comment]
Thanks for the report @wolftune !

The `bambam.desktop` file is not directly executable from a shell. It is meant to be copied to the `applications` directory where KDE would be able to find them and make them available through the applications menu.

There is also `bambam-session.desktop` which is similar, but meant to be copied into a `sessions` directory where it can 
be used to run **instead** of KDE.

Note, that using the `.desktop` files requires some minor but important processing beforehand.
See https://github.com/porridge/bambam?tab=readme-ov-file#manual-installation for details.

Note that neither of the desktop files currently let you use the extensions feature. You'd have to additionally edit them to add the necessary flag.

However, if you only want to try the `master` version out quickly, you can run `bambam.py` from a shell, see https://github.com/porridge/bambam?tab=readme-ov-file#usage

Please let me know how it goes!

**Comment by wolftune** [comment]
For now, I'm happy to just test it the quickest I can. I tried the .py but got this:

```
$ ./bambam.py 
pygame 2.1.2 (SDL 2.28.5, Python 3.10.12)
Hello from the pygame community. https://www.pygame.org/contribute.html
Using data directory /home/aaron/Downloads/extract-temp/bambam-master/data
Using extension directory /home/aaron/Downloads/extract-temp/bambam-master/extensions
Using data directory /home/aaron/.local/share/bambam/data
Traceback (most recent call last):
  File "/home/aaron/Downloads/extract-temp/bambam-master/./bambam.py", line 754, in <module>
    main()
  File "/home/aaron/Downloads/extract-temp/bambam-master/./bambam.py", line 747, in main
    bambam.run()
  File "/home/aaron/Downloads/extract-temp/bambam-master/./bambam.py", line 554, in run
    pygame.init()
RuntimeError: SDL compiled with version 2.0.20, linked to 2.28.5
```

**Comment by wolftune** [comment]
Yes, that gives the same `RuntimeError: SDL compiled with version 2.0.20, linked to 2.28.5`

**Comment by porridge** [comment]
Any updates from your side on this one @wolftune ?

I guess this would be solved if we made self-contained binaries that did not depend on distribution's Python, pygame, etc. I think I tried this one but did not get far. :-(

**Comment by wolftune** [comment]
I don't know why this would change for my. Again `python3 -c 'import pygame;pygame.init()'` has the error, so this isn't bambam specific. I don't know what to do. But if you want me to try something, let me know

**Comment by porridge** [comment]
I thought maybe you upgraded your packages and this went away @wolftune 
What distribution are you using?

**Comment by wolftune** [comment]
I'm on KDE Neon user edition. I also have my son using an Ubuntu laptop, and I could test it there too easily enough, have not tried yet

**Comment by porridge** [comment]
I quickly ran a KDE Neon container, and it looks like this problem is specific to that distribution:

```
neon@9903ad8760fc:~$ sudo apt install python3-pygame
[...]
neon@9903ad8760fc:~$ sudo apt policy python3-pygame
python3-pygame:
  Installed: 2.1.2+dfsg-3
  Candidate: 2.1.2+dfsg-3
  Version table:
 *** 2.1.2+dfsg-3 500
        500 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
        100 /var/lib/dpkg/status
neon@9903ad8760fc:~$ sudo apt policy libsdl2-2.0-0
libsdl2-2.0-0:
  Installed: 2.28.5+dfsg-2+22.04+jammy+release+build2
  Candidate: 2.28.5+dfsg-2+22.04+jammy+release+build2
  Version table:
 *** 2.28.5+dfsg-2+22.04+jammy+release+build2 500
        500 http://archive.neon.kde.org/user jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     2.0.20+dfsg-2ubuntu1.22.04.1 500
        500 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages
     2.0.20+dfsg-2build1 500
        500 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages
neon@9903ad8760fc:~$ python3 -c 'import pygame;pygame.init()'
pygame 2.1.2 (SDL 2.28.5, Python 3.10.12)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "<string>", line 1, in <module>
RuntimeError: SDL compiled with version 2.0.20, linked to 2.28.5
```

Looks like the KDE Neon team built a newer SDL, but did not upgrade pygame to match? I [asked for help](https://discuss.kde.org/t/using-pygame-on-kde-neon/17049) on the KDE discuss forum.

**Comment by wolftune** [comment]
Okay thanks, I guess I should just test on the other system to confirm and see that it works. And otherwise, this issue could be closed with reference to upstream Neon issue… (let me know if you want me to open a ticket with KDE, I do use their bug-tracker)

**Comment by porridge** [comment]
It [seems unlikely](https://discuss.kde.org/t/using-pygame-on-kde-neon/17049/5?u=marcin_owsiany) that neon will provide a pygame compatible with the SDL it ships.

However it should be possible to install a recent pygame in your user's home directory. The following commands install it in `~/.local/lib/` for me:

```
sudo apt install python3-pip
python3 -m pip install -U pygame --user
```

and then pygame seems to work for me:

```
python3 -c 'import pygame;pygame.init()'
```

You might also want to wipe the broken system-provided pygame:
```
sudo apt purge python3-pygame
```

Please let me know if this works for you.

**Comment by wolftune** [comment]
that works, I got it to run now
