### ISSUE TITLE
Allow drawing with the mouse without having to hold a button down

### ISSUE THREAD

**Issue by ngm** [porridge/bambam#136]
My 8 month old bubba is enjoying bambam very much, thank you!  Much more fun than a text editor with a large font size, what I had been using before.

One improvement that could be nice - they aren't yet able to move the mouse while holding a button down.  So we don't get to use the drawing feature.  If it would be possible for a config option to allow drawing while no button is pressed, that would be great.  Or perhaps even a button that I can press while bambam is open to toggle button-free drawing on and off.

**Comment by porridge** [comment]
Great idea @ngm !
I'll take a stab at adding a command to do this next week.

**Comment by porridge** [comment]
I managed to do this today. I'll give translators some time to update and hope to release 1.4.0 with this feature this week.
You can try this out by downloading the tip of `master` before then.
