### ISSUE TITLE
Blocking [CTRL-]Alt-Fx ? 

### ISSUE THREAD

**Issue by thorsig** [porridge/bambam#16]
Hi,

My toddler has been thoroughly enjoying BamBam on his own computer while daddy is working on his. 

But of late, he has managed to switch to a different VTY.

I didn't find any immendiate solution (read: I was lazy and didn't search thoroughly if at all possible), but I wonder if this can be blocked at all?

(Sorry for crossposting in the google-group as well)

**Comment by porridge** [comment]
https://ubuntuforums.org/showthread.php?t=2146928&p=12655703#post12655703
Please let us know whether this actually helps.
If it does, then it's worth adding to README and/or manpage.

**Comment by thorsig** [comment]
Apparently, it works :)

It does however have the (probably unwanted) side-effect that if you fail
your login (wrong password etc) then gdm seems to bork.

So, secondary solution: sudo apt install openssh-server  and be ready to
ssh into the locked-up machine and reboot it (restarting gdm3 wasn't enough
in my case).

Anyhow - case closed from my toddler's point of view :)

2016-12-05 5:36 GMT+00:00 Marcin Owsiany <notifications@github.com>:
