### ISSUE TITLE
SyntaxWarning about "is" operator

### ISSUE THREAD

**Issue by vn971** [porridge/bambam#33]
Hi. When I try to run bambam on my ArchLinux system with python3, I get the following error:
```
/usr/bin/bambam:100: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if colorkey is -1:
Traceback (most recent call last):
  File "/usr/bin/bambam", line 23, in <module>
    import pygame
ModuleNotFoundError: No module named 'pygame'
```

If I change the header of the file to `python2`, however, everything works. That means that it's some code that needs to be ported to python3, am I correct? Can you please do that (or temporarily revert to python2)?

Thanks for the project again!

**Comment by vn971** [comment]
Wait, I didn't have `python-pygame` installed :man_facepalming: . It works with it though! Closing.

**Comment by porridge** [comment]
The messages you pasted show two issues. The latter you fixed. Reopening for the former warning.
